[build]
  command = "npm run build"  # Ensures that your package scripts are run
  publish = ".next"  # Use 'out' for static exports if running 'next export'

[context.production]
  environment = { 
    NODE_ENV = "production"
  }

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Make sure you're using the plugin for Next.js
